---
- project:
    queue: masakari
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
      - periodic-jobs-with-oslo-master
    check:
      jobs:
        - openstack-tox-linters
        - masakari-functional-devstack-multinode
        - masakari-functional-devstack-ipv6
    gate:
      jobs:
        - openstack-tox-linters
        - masakari-functional-devstack-multinode
        - masakari-functional-devstack-ipv6
