[DEFAULT]
output_file = etc/masakarimonitors/masakarimonitors.conf.sample
wrap_width = 80
namespace = masakarimonitors.conf
namespace = oslo.concurrency
namespace = oslo.log
namespace = oslo.service.periodic_task
namespace = oslo.service.service
